# Generated by Django 4.2.6 on 2023-10-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_url',
            field=models.URLField(default='https://avatars.mds.yandex.net/i?id=7d5945d1f087f0300f467e9b4eac093999aa67d0-9853689-images-thumbs&n=13'),
        ),
    ]
