# Generated by Django 4.2.6 on 2023-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='./media'),
        ),
    ]
