# Generated by Django 4.2.6 on 2023-10-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_url',
        ),
    ]
