# Generated by Django 4.2.6 on 2023-10-25 13:48

from django.db import migrations, models
import django_resized.forms
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default/no-photo-min.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to=product.models.content_file_name),
        ),
    ]
