# Generated by Django 4.2.6 on 2023-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('open', 'счёт открыт'), ('check', 'ожидает оплаты'), ('pay', 'оплачен')], default='open', max_length=12),
        ),
    ]
