# Generated by Django 4.2.6 on 2023-11-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_p', '0001_initial'),
        ('orders', '0006_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('table_id', 'status')},
        ),
    ]
