# Generated by Django 4.2.6 on 2023-11-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together=set(),
        ),
    ]
