# Generated by Django 4.2.6 on 2023-11-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
        ('orders', '0008_alter_orders_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.tablemodel'),
        ),
    ]
