# Generated by Django 4.2.6 on 2023-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorders',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
