# Generated by Django 4.2.6 on 2023-12-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_description'),
        ('orders', '0011_alter_itemorders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
