# Generated by Django 4.2.6 on 2023-10-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo_url',
        ),
    ]
