# Generated by Django 4.2.6 on 2023-11-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_table_id'),
        ('admin_p', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableModel',
        ),
    ]
